
service: rekognition-DetectRecognizeFace

provider:
  name: aws
  runtime: nodejs8.10

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:GetObject
        - s3:DeleteObject
      Resource: arn:aws:s3:::image2texttestvideos/*
    - Effect: Allow
      Action: 
        - rekognition:StartFaceSearch
      Resource: "*"

functions:
  StartImage2text_001:
    handler: handler.StartImage2text_001
    events:
      - s3:
          bucket: image2texttestvideos 
          event: s3:ObjectCreated:*
