
service: rekognition-DetectRecognizeFace

provider:
  name: aws
  runtime: nodejs8.10

  iamRoleStatements:
    - Effect: Allow
      Action: 
        - rekognition:GetFaceSearch
      Resource: "*"

functions:
  GetImage2textResult_001:
    handler: handler.GetImage2textResult_001
    events:
      - httpApi:
          path: /getresult
          method: post
