
service: rekognition-TrainImage 

provider:
  name: aws
  runtime: nodejs8.10

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:GetObject
        - s3:DeleteObject
      Resource: arn:aws:s3:::image2texttraindata/*
    - Effect: Allow
      Action: 
        - rekognition:index-faces
      Resource: "*"

functions:
  TrainImage2text_001:
    handler: handler.TrainImage2text_001
    events:
      - s3:
          bucket: image2texttraindata 
          event: s3:ObjectCreated:*
